import {readFile} from 'node:fs/promises';
const pkg=JSON.parse(await readFile('package.json','utf8'));
const tag=process.env.RELEASE_TAG||`quota-otter-v${pkg.version}`;
if(!/^quota-otter-v\d+\.\d+\.\d+$/.test(tag||''))throw Error('Release tags must be quota-otter-vMAJOR.MINOR.PATCH');
const expected=tag.slice('quota-otter-v'.length);
const tauri=JSON.parse(await readFile('src-tauri/tauri.conf.json','utf8'));
const cargo=await readFile('src-tauri/Cargo.toml','utf8');
const packageSection=cargo.split(/^\s*\[/m).find(section=>section.startsWith('package]'));
const cargoVersion=packageSection?.match(/^\s*version\s*=\s*["']([^"']+)["']\s*(?:#.*)?$/m)?.[1];
if(pkg.version!==expected||tauri.version!==expected||cargoVersion!==expected)throw Error('Package, Cargo and Tauri versions must match the release tag.');
const lock=JSON.parse(await readFile('package-lock.json','utf8'));
const cargoLock=await readFile('src-tauri/Cargo.lock','utf8');
const ownPackage=cargoLock.split('[[package]]').find(section=>/^name = "quota-otter"$/m.test(section));
const lockedVersion=ownPackage?.match(/^version = "([^"]+)"$/m)?.[1];
const ui=await readFile('src/version.js','utf8');
if(lock.version!==expected||lock.packages?.['']?.version!==expected||lockedVersion!==expected||!ui.includes(`APP_VERSION = '${expected}'`))throw Error('Lockfile and UI versions must match the release tag.');
console.log(`Versions agree: ${expected}`);
